Pdq miglioramento
merlunipd/login-warrior pull request #115
Opened 2022-02-10 15:17 UTC by LorenzoOnelia

2022-02-10 15:18 UTC, LorenzoOnelia commented
Nella colonna "problema" lascio responsabile o cosa va messo? Non capisco il senso tbh

2022-02-10 15:58 UTC, MattiaZanellato commented
Riga 19: non mi suona bene il termine "rubato"

2022-02-11 14:56 UTC, MattiaZanellato commented
> Fixato, se vedi un merge strano ha fatto tutto atom perchè purtroppo mi ero dimenticato di fetchare

Non mi sembra di vedere problemi di questo tipo, non so bene a cosa ti riferisci

2022-02-11 14:57 UTC, MattiaZanellato commented
Alla fine rimane la scritta "Responsabile" nella colonna del problema?

2022-02-11 15:44 UTC, LorenzoOnelia commented
> Alla fine rimane la scritta "Responsabile" nella colonna del problema?

Eh alla fine ci siamo dimenticati di prendere una decisione.. scrivo su wa

2022-02-19 08:19 UTC, MattiaZanellato requested changes

2022-02-19 08:19 UTC, MattiaZanellato commented on src/documenti/esterni/PdQ/contenuti/miglioramento.tex
> +    Responsabile & Media & Durante il periodo della terza milestone, dal 15/01/2022 al 04/02/2022, il gruppo si è reso conto di non essere in grado di rispettare le ore preventivate. La presenza dell
Bisogna fare qualcosa per questo "responsabile"

2022-02-19 09:52 UTC, LorenzoOnelia commented on src/documenti/esterni/PdQ/contenuti/miglioramento.tex
> +    Responsabile & Media & Durante il periodo della terza milestone, dal 15/01/2022 al 04/02/2022, il gruppo si è reso conto di non essere in grado di rispettare le ore preventivate. La presenza dell
Metto organizzativo

2022-02-19 11:02 UTC, MattiaZanellato approved these changes

2022-02-19 11:03 UTC, merged