PdP-MitigazioneDeiRischi
merlunipd/login-warrior pull request #117
Opened 2022-02-11 14:51 UTC by MattiaZanellato

2022-02-12 16:17 UTC, riccardo-contin requested changes
In sé non ci sono errori. Fatta così, effettivamente, risulta troppo un copia-incolla dell'analisi. Secondo me tra questi andrebbero trattati solo i rischi che effettivamente sono già diventati realtà e analizzare cosa hanno provocato e se siamo riusciti effettivamente a mitigare con il piano che avevamo stabilito.
C'è, per essere più chiari, se un rischio è diventato veramente realtà e ha causato ritardi, allora ci sta scrivere qualche riga su com'è stato affrontato, altrimenti scriverei soltanto "non verificato"

2022-02-12 16:21 UTC, riccardo-contin commented
Per esempio, il rischio della disponibilità, allora là sì scriverei che nonostante l'analisi di partenza, preventivi troppo ottimistici hanno causato ritardi che si sono dovuti risolvere successivamente = piano di contingenza non ha funzionato

2022-02-12 16:25 UTC, riccardo-contin commented
Nei problemi interpersonali, invece, secondo me le precauzioni sono state sufficienti => piano di contingenza non necessario perchè non si sono verificati scontri

2022-02-14 10:54 UTC, MattiaZanellato commented
Ho aggiornato le "mitigazioni" tenendo maggiormente conto dell'analisi dei rischi in modo che non risulti una ripetizione ma un collegamento a quella parte

2022-02-18 14:53 UTC, merged