Fuffa AdR
merlunipd/login-warrior pull request #145
Opened 2022-03-04 13:19 UTC by LorenzoOnelia

2022-03-04 13:21 UTC, LorenzoOnelia commented
Ho alcune domande: 
- il requisito di qualità che ho inserito (manuale sviluppatore) va bene come desiderabile o è meglio opzionale?
- nella tabella Fonte - Requisiti dove va inserito questo requisito? Sotto Capitolato come gli altri?

2022-03-04 14:31 UTC, MattiaZanellato commented
> Ho alcune domande:
> 
> * il requisito di qualità che ho inserito (manuale sviluppatore) va bene come desiderabile o è meglio opzionale?
> * nella tabella Fonte - Requisiti dove va inserito questo requisito? Sotto Capitolato come gli altri?

- il requisito è richiesto nel capitolato quindi è obbligatorio
- si sotto capitolato, e va inserito anche nella tabella requisito - fonti

2022-03-04 14:31 UTC, MattiaZanellato requested changes
vedi commento sopra

2022-03-04 14:32 UTC, MattiaZanellato commented
la lista di distribuzione aggiungila anche agli altri file

2022-03-04 14:35 UTC, LorenzoOnelia commented
Va aggiunta anche la voce sulla tabella delle modifiche? Ho un vuoto, mi sembra di si però

2022-03-04 15:49 UTC, MattiaZanellato commented
> Va aggiunta anche la voce sulla tabella delle modifiche? Ho un vuoto, mi sembra di si però

si va aggiunta, inserendola prima dell'approvazione finale

2022-03-04 16:04 UTC, MattiaZanellato commented
Per quanto riguarda il frontespizio, va chiesto agli altri se piace e se va bene.
Per me sarebbe carino visualizzarlo non in stile tabellare ma più come abbiamo visto dagli altri casi

2022-03-04 18:17 UTC, MattiaZanellato commented
Ok così il frontespizio mi piace di più, senti comunque se piace agli altri

2022-03-04 22:56 UTC, LorenzoOnelia commented
Agli altri va bene. È da apposto la pull?

2022-03-05 11:57 UTC, morokuz commented
Secondo voi sarebbe il caso di aggiornare anche il frontespizio del glossario sul drive? In caso @LorenzoOnelia sarebbe da esportare in PDF e sostituire in `documenti/Glossario.pdf`, così viene mergato insieme a tutte le altre modifiche

2022-03-05 13:18 UTC, MattiaZanellato commented
> Secondo voi sarebbe il caso di aggiornare anche il frontespizio del glossario sul drive? In caso @LorenzoOnelia sarebbe da esportare in PDF e sostituire in `documenti/Glossario.pdf`, così viene mergato insieme a tutte le altre modifiche

a questo punto direi di si

2022-03-05 13:18 UTC, MattiaZanellato commented
> Agli altri va bene. È da apposto la pull?

aggiungi solo la cosa del glossario, il resto mi sembra ok

2022-03-05 15:18 UTC, MattiaZanellato commented
@morokuz è giusto "Uso Esterno"? Ho un dubbio perché il glossario serve più a noi, non saprei. Comunque se è corretto allora va tutto bene e si può mergiare, altrimenti è l'unica cosa da cambiare

2022-03-05 16:29 UTC, morokuz commented
> @morokuz è giusto "Uso Esterno"? Ho un dubbio perché il glossario serve più a noi, non saprei. Comunque se è corretto allora va tutto bene e si può mergiare, altrimenti è l'unica cosa da cambiare

Si si è ad uso esterno, come è segnato nelle NdP (visto che può essere utile anche al proponente e/o al committente oltre che a noi, vince l'uso più permissivo)

2022-03-05 17:24 UTC, MattiaZanellato approved these changes

2022-03-06 15:19 UTC, merged