Glossario
merlunipd/login-warrior pull request #148
Opened 2022-03-05 13:43 UTC by morokuz

Aggiunte `G` nei documenti in corrispondenza ai termini del glossario. Aggiornate NdP. Uniformate le sezioni Glossario nelle introduzioni a tutti i documenti

2022-03-06 16:35 UTC, MattiaZanellato commented
Sto guardando parola per parola e noto che la G a pedice è staccata dalla parola corrispondente, forse potrebbe creare confusione? In caso per modificarle basterebbe fare un CTRL+F cercando " $_G$" e fare replace all con "$_G$". In teoria in questo modo viene tolto lo spazio da tutte le occorrenze e diventa più veloce da fixare. Però dimmi pure se era voluta come cosa o meno.

2022-03-06 16:44 UTC, morokuz commented
> Sto guardando parola per parola e noto che la G a pedice è staccata dalla parola corrispondente, forse potrebbe creare confusione? In caso per modificarle basterebbe fare un CTRL+F cercando " $_G$" e fare replace all con "$_G$". In teoria in questo modo viene tolto lo spazio da tutte le occorrenze e diventa più veloce da fixare. Però dimmi pure se era voluta come cosa o meno.

Yes, era intenzionale perché attaccato mi sembrava meno piacevole. Però non ho forti preferenze e come dici tu è un "replace all" veloce da fare. Se tu dici che è meglio attaccato lo correggo subito! Se invece è ok anche così lo lasciamo e in caso lo modifichiamo più avanti

2022-03-06 16:47 UTC, MattiaZanellato commented
> 

Non so perché averlo attaccato fa capire a cosa si riferisce, staccandolo mi dà la sensazione di essere un po' nella "terra di nessuno".
Comunque ora sto controllando parola per parola e poi faccio la revisione in un unico commento

2022-03-06 17:42 UTC, MattiaZanellato requested changes
- "branch" in NdP è segnato con la G a pagina 32 (sezione 4.1.2), la prima occorrenza avviene a pagina 25 (sezione 3.4.3)
- "ciclo di vita" in NdP è segnato con la G sia a pagina 9 (sezione 2.2.1) sia a pagina 12 (sezione 3.1.1)
- "configurazione" in NdP è segnato con la G sia a pagina 19 (sezione 3.2.3) sia a pagina 32 (sezione 4.1.2)
- "consuntivo" in PdP è segnato con la G sia a pagina 8 (sezione 1.1) sia a pagina 35 (sezione 6)
- "convenzione" non è presente al singolare nei 4 documenti. È presente "convenzioni" in NdP con la prima occorrenza a pagina 6 (sezione 1.1), vedi tu che fare
- "diagrammi uml" in NdP è segnato con la G sia a pagina 11 (sezione 2.2.4) sia a pagina 17 (sezione 3.1.18)
- "git" in NdP a pagina 19 non ha la G a pedice
- "github" in NdP è segnato con la G sia a pagina 12 (sezione 3.1.4) sia a pagina 28 (sezione 4.1.1)
- "indice di gulpease" in PdQ è segnato con la G a pagina 18 (sezione 5.2.1), ma prima c'è un'occorrenza (non in tabelle o robe strane, ma in corsivo, forse questo te lo ha fatto saltare) a pagina 17 (sezione 5.1)
- "json" in AdR è segnato con la G sia a pagina 10 (sezione 2.2) sia a pagina 13 (sezione 3.3)
- "metrica" in PdQ non ha la G a pagina 17 (sezione 5.2.1), le occorrenze prima sono nelle tabelle quindi diventa automaticamente la prima questa
- "poc" in NdP non ha la G a pagina 10 (sezione 2.2.4)
- "preventivo" in PdP è segnato con la G sia a pagina 8 (sezione 1.1) sia a pagina 18 (sezione 4.1.1) sia a pagina 35 (sezione 6)
- "proponente" in AdR è segnato con la G sia a pagina 8 (sezione 1.1) sia a pagina 21 (sezione 4.5)
- "proponente" in PdP è segnato con la G sia a pagina 10 (sezione 2.1) sia a pagina 11 (sezione 3)
- "proponente" in NdP è segnato con la G sia a pagina 8 (sezione 2.1.1) sia a pagina 13 (sezione 3.1.6)
- "pull request" in NdP è segnato con la G sia a pagina 19 (sezione 3.2.5) sia a pagina 30 (sezione 4.1.2) sia a pagina 32 (sezione 4.1.2)
- "repository" in NdP è segnato con la G sia a pagina 13 (sezione 3.1.4) sia a pagina 34 (sezione 4.2.1)
- "retrospettiva" c'è al plurale in NdP a pagina 21 (sezione 3.3.2)
- "sankey diagram in AdR è segnato con la G sia a pagina 14 (sezione 3.5) sia a pagina 15 (sezione 3.5.4)
- "validazione" in NdP è segnato con la G sia a pagina 9 (sezione 2.2.1) sia a pagina 26 (sezione 3.5.3)
- "verifica" in NdP è segnato con la G sia a pagina 9 (sezione 2.2.1) sia a pagina 12 (sezione 3.1.2)
- "zoom" nel glossario inizialmente aveva due significati (piattaforma e zoom del grafico). Lo zoom del grafico era tra i filtri dei dati che però ora sono cambiati, non so se nella personalizzazione lo abbiano messo, altrimenti sarebbe da togliere dal glossario per lasciare solo zoom come piattaforma

2022-03-07 12:01 UTC, morokuz commented
Grazie ancora per il commento super-dettagliato! 

Un problema che ho avuto è che guardando i file LaTeX non ci sono riferimenti al numero delle capitoli / sezioni / sottosezioni / etc, ne alle pagine :/ quindi a volte è un po' complesso (bisogna fare avanti e indietro tra latex e PDF)...

Comunque ho corretto le parti mancanti ma ho lasciato le ripetizioni.

2022-03-07 12:58 UTC, MattiaZanellato commented
> 

In effetti non avevo considerato che nei file effettivamente non ci sono riferimenti. Sarebbe stato sicuramente più utile indicare il file e la riga al suo interno, prossima volta farò così.

2022-03-07 12:59 UTC, MattiaZanellato approved these changes

2022-03-08 08:12 UTC, merged