Pdp-sprint6-consuntivo
merlunipd/login-warrior pull request #202
Opened 2022-04-06 09:17 UTC by LorenzoOnelia

2022-04-06 10:45 UTC, riccardo-contin requested changes

2022-04-06 10:45 UTC, riccardo-contin commented on src/documenti/esterni/PdP/contenuti/consuntivo.tex
> +            \rowcolor[HTML]{EFEFEF}\textit{Lorenzo Onelia}   & 4.5      & -          & -          & 2          & 1 (-1)   & 2        & 9.5 (-0.5)       \\ \hline
Manca l'indicazione (+0.5) su Responsabile

2022-04-06 10:45 UTC, riccardo-contin commented on src/documenti/esterni/PdP/contenuti/consuntivo.tex
> +    \rowcolor[HTML]{EFEFEF}\textit{Marko Vukovic}    & 0    & 0    & 0     & 4     & 19  & 7      & 30     \\ \hline
Le ore da progettista di Marco non sono 6?

2022-04-06 10:45 UTC, riccardo-contin commented on src/documenti/esterni/PdP/contenuti/consuntivo.tex
> +    \caption{Consuntivo dei costi per la sesta milestone}
Di solito si è messo la differenza anche qua rispetto al preventivo

2022-04-06 10:52 UTC, LorenzoOnelia commented on src/documenti/esterni/PdP/contenuti/consuntivo.tex
> +    \rowcolor[HTML]{EFEFEF}\textit{Marko Vukovic}    & 0    & 0    & 0     & 4     & 19  & 7      & 30     \\ \hline
No alla fine abbiamo visto che c'era stato un errore nel consuntivo 5

2022-04-06 10:52 UTC, LorenzoOnelia commented on src/documenti/esterni/PdP/contenuti/consuntivo.tex
> +            \rowcolor[HTML]{EFEFEF}\textit{Lorenzo Onelia}   & 4.5      & -          & -          & 2          & 1 (-1)   & 2        & 9.5 (-0.5)       \\ \hline
grazie

2022-04-06 10:57 UTC, LorenzoOnelia commented on src/documenti/esterni/PdP/contenuti/consuntivo.tex
> +    \caption{Consuntivo dei costi per la sesta milestone}
Non capisco, non è quello che ho fatto?

2022-04-06 12:05 UTC, riccardo-contin commented on src/documenti/esterni/PdP/contenuti/consuntivo.tex
> +    \caption{Consuntivo dei costi per la sesta milestone}
Anche con le parentesi come nel consuntivo orario

2022-04-07 07:45 UTC, LorenzoOnelia commented
Ora dovrebbe essere apposto, prova a controllare

2022-04-07 10:18 UTC, riccardo-contin approved these changes

2022-04-07 16:04 UTC, merged