PdP - Preventivo 11
merlunipd/login-warrior pull request #272
Opened 2022-05-07 10:24 UTC by LorenzoOnelia

2022-05-07 11:25 UTC, riccardo-contin requested changes
Dovresti anche aggiungere un paio di righe nel capitolo Pianificazione

2022-05-07 11:25 UTC, riccardo-contin commented on src/documenti/esterni/PdP/contenuti/preventivo.tex
> +    \includegraphics[width=1.0\textwidth]{Torta11.1.jpg}
Se riesci togli l'etichetta con lo 0%

2022-05-07 11:25 UTC, riccardo-contin commented on src/documenti/esterni/PdP/contenuti/preventivo.tex
> +    \item Risolvere il baco nello Scatter Plot 2;
Ho lasciato un commento sulla issue per capire se è veramente necessario poiché nel grafico non ci sono i logout

2022-05-07 11:25 UTC, riccardo-contin commented on src/documenti/esterni/PdP/contenuti/preventivo.tex
> +    \includegraphics[width=1.0\textwidth]{Torta11.2.jpg}
Se riesci togli l'etichetta con lo 0%

2022-05-09 08:00 UTC, LorenzoOnelia commented
> Dovresti anche aggiungere un paio di righe nel capitolo Pianificazione

Non va bene già così com'è? Abbiamo deciso di non scrivere più niente nella pianificazione e di fare tutto direttamente nel preventivo

2022-05-09 09:29 UTC, riccardo-contin commented
In realtà un paio di righe che riassumono velocemente cosa si andrà a fare in quel periodo le abbiamo messe anche gli scorsi sprint mi sembra

2022-05-09 09:31 UTC, LorenzoOnelia commented
È vero, nel preventivo precedente al mio non è stato fatto e questo mi ha messo confusione. Ora aggiungo entrambi

2022-05-13 16:15 UTC, merged