Verbale con proponente 11/01/2022
merlunipd/login-warrior pull request #74
Opened 2022-01-12 09:59 UTC by MattiaZanellato

2022-01-12 10:00 UTC, MattiaZanellato commented
Da capire se  inserirlo come verbale interno o definirlo in maniera diversa

2022-01-12 10:30 UTC, mamprinmarco commented
Io la vedo così:
-Verbali interni, riunioni tra di noi del gruppo, qualcosa di interno al gruppo
-Verbali esterni, riunioni o incontri con i professori o con il proponente, quindi qualcosa di esterno dal gruppo come in questo caso

2022-01-12 11:27 UTC, MattiaZanellato commented
Ok avrebbe in effetti senso come cosa. Intanto lascio così poi alla riunione di oggi pomeriggio chiediamo se va bene e in caso cambio

2022-01-15 11:33 UTC, mamprinmarco approved these changes

2022-01-16 09:57 UTC, Emanuele999-it requested changes
Il pdf non viene compilato perché non esiste la cartella "immagini" con path "shared/immagini" nei verbali esterni

2022-01-16 10:14 UTC, MattiaZanellato commented
Ho risolto cambiando il path delle immagini in modo da non dover sdoppiare la cartella delle immagini. Ditemi cosa ne pensate.

2022-01-16 10:27 UTC, Emanuele999-it commented
Io sinceramente duplicherei la cartella visto che le immagini in comune non pesano così tanto, sentiamo cosa dice @mamprinmarco

2022-01-16 10:30 UTC, mamprinmarco commented
> Io sinceramente duplicherei la cartella visto che le immagini in comune non pesano così tanto, sentiamo cosa dice @mamprinmarco

Anch'io la penso così, alla fine abbiamo solo due immagini piccole, quindi non ci dovrebbero essere problemi, sia mai che cambiamo struttura della repo e ti diventi pazzo ad aggiustare il path condiviso

2022-01-16 11:15 UTC, MattiaZanellato commented
Ok perfetto, ho duplicato la cartella immagini, dovrebbe essere apposto

2022-01-16 11:49 UTC, mamprinmarco approved these changes

2022-01-16 11:50 UTC, mamprinmarco commented
Dovrebbere essere tutto ok

2022-01-16 12:03 UTC, Emanuele999-it approved these changes

2022-01-16 12:03 UTC, merged